<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.laporeon</groupId>
	<artifactId>keeplybot</artifactId>
	<version>1.0.0-SNAPSHOT</version>
  <packaging>jar</packaging>
	<name>Keeply Bot</name>
	<description>Like a bookmark for your Discord chats. Save messages, revisit them later.</description>
	<licenses>
		<license>
			<name>GNU General Public License v3.0</name>
			<url>https://opensource.org/license/gpl-3.0</url>
		</license>
	</licenses>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>21</maven.compiler.release>
		<main.class>com.laporeon.keeplybot.KeeplyApplication</main.class>
		<maven.shade.plugin.version>3.6.0</maven.shade.plugin.version>
    <dotenv.version>3.2.0</dotenv.version>
    <jda.discord.version>6.7.0</jda.discord.version>
    <logback.classic.version>1.6.3</logback.classic.version>
    <exec.maven.plugin.version>3.6.4</exec.maven.plugin.version>
	</properties>

	<dependencies>
    <dependency>
      <groupId>io.github.cdimascio</groupId>
      <artifactId>dotenv-java</artifactId>
      <version>${dotenv.version}</version>
    </dependency>
    <dependency>
      <groupId>net.dv8tion</groupId>
      <artifactId>JDA</artifactId>
      <version>${jda.discord.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>${logback.classic.version}</version>
    </dependency>
	</dependencies>

	<build>
    <finalName>keeplybot</finalName>
		<plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>${maven.shade.plugin.version}</version>
        <executions>
          <execution>
            <id>shade</id>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/MANIFEST.MF</exclude>
                    <exclude>META-INF/LICENSE*</exclude>
                    <exclude>META-INF/NOTICE*</exclude>
                    <exclude>META-INF/maven/**</exclude>
                    <exclude>META-INF/versions/**/module-info.class</exclude>
                    <exclude>module-info.class</exclude>
                  </excludes>
                </filter>
              </filters>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>${main.class}</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>${exec.maven.plugin.version}</version>
        <configuration>
          <mainClass>${main.class}</mainClass>
        </configuration>
      </plugin>
		</plugins>
	</build>

</project>
